name: Build Windows Release (MSVC)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-msvc:
    runs-on: windows-2022 
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: microsoft/setup-msbuild@v2

      - name: Build with nmake
        run: cd Controller && nmake /f Makefile
        shell: cmd

      - name: Package Release
        run: |
          mkdir output
          powershell Compress-Archive -Path Controller\*.exe -DestinationPath output\release.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: output/release.zip
