name: Build Windows Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 可选：安装 CMake
      - name: Install CMake
        uses: lukka/get-cmake@latest

      # 安装 MinGW
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2

      # 进入 Controller 文件夹并生成构建目录
      - name: Configure CMake
        run: cmake -S Controller -B build -G "MinGW Makefiles"

      # 编译
      - name: Build
        run: cmake --build build --config Release

      # 打包可执行文件
      - name: Package Release
        run: |
          mkdir build\output
          powershell Compress-Archive -Path build\*.exe -DestinationPath build\output\release.zip

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: build/output/release.zip
