name: Build CSOL-Utilities

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 运行器，因为这是 .NET 项目

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # 使用 .NET 7.0
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CSOL-Utilities
        path: publish/
