name: Build Windows Release (C++ with g++)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-gpp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW-w64
        run: choco install mingw
        shell: cmd

      - name: Build with GNU Make (g++)
        run: |
          set "PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%"
          make -f Makefile
        shell: cmd

      - name: Package Release
        run: |
          mkdir output
          powershell Compress-Archive -Path Controller\*.exe -DestinationPath output\release.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: output/release.zip
