name: Build Windows Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build (MinGW, Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 安装 CMake
      - name: Install CMake
        uses: lukka/get-cmake@latest

      # 安装 MinGW
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2

      # 可选：删除 libpthread.dll.a（不会因不存在报错）
      - name: Remove libpthread.dll.a if exists
        run: |
          $mingw_lib = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib"
          Remove-Item (Join-Path $mingw_lib 'libpthread.dll.a') -ErrorAction SilentlyContinue
        shell: pwsh

      # 进入 Controller 文件夹并生成 build 目录
      - name: Configure CMake
        run: cmake -S Controller -B build -G "MinGW Makefiles"

      # 编译
      - name: Build
        run: cmake --build build --config Release

      # 打包可执行文件
      - name: Package Release
        run: |
          mkdir build\output
          powershell Compress-Archive -Path build\*.exe -DestinationPath build\output\release.zip

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: build/output/release.zip
