name: Build Windows Release (MSVC absolute nmake)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug workspace
        run: |
         dir
         dir Controller
        shell: cmd

      - name: Build with nmake (add to PATH)
        run: |
         cd Controller
         call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
         set "PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64;%PATH%"
         nmake /f Makefile
        shell: cmd

      - name: Package Release
        run: |
          mkdir output
          powershell Compress-Archive -Path Controller\*.exe -DestinationPath output\release.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: output/release.zip
