name: Build Windows Release (MSVC)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with MSVC nmake
        run: |
          cd Controller
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          nmake /f Makefile
        shell: cmd

      - name: Package Release
        run: |
          mkdir output
          powershell Compress-Archive -Path Controller\*.exe -DestinationPath output\release.zip
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release
          path: output/release.zip
